GLOBAL.STRINGS.CHARACTERS.WURT.ANNOUNCE_SWIMTOOL = "Can't swim with full claws, glorp."
GLOBAL.STRINGS.CHARACTERS.WURT.ANNOUNCE_DONESWIM = "Maybe swim more later, florpt."
GLOBAL.STRINGS.CHARACTERS.WURT.ANNOUNCE_PRESWIM = "Feel like swimming, florpt!"
GLOBAL.STRINGS.CHARACTERS.WURT.ANNOUNCE_NOSWIM = "No feel like swim now."

--wilson and everybody else unspecified (in case modded character or something)
GLOBAL.STRINGS.CHARACTERS.GENERIC.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DONESWIM = "I prefered my beard with food pieces in it, but oh well"
GLOBAL.STRINGS.CHARACTERS.GENERIC.ANNOUNCE_PRESWIM = "All that thinking made my head hot, maybe it's time for a swim"
GLOBAL.STRINGS.CHARACTERS.GENERIC.ANNOUNCE_NOSWIM = "Changed my mind, science can't wait"

GLOBAL.STRINGS.CHARACTERS.WILLOW.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WILLOW.ANNOUNCE_DONESWIM = "That was terrible, need to light something on fire"
GLOBAL.STRINGS.CHARACTERS.WILLOW.ANNOUNCE_PRESWIM = "Not sure I like where this is going"
GLOBAL.STRINGS.CHARACTERS.WILLOW.ANNOUNCE_NOSWIM = "Uff, got me worried for a second"

GLOBAL.STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_SWIMTOOL = "Wolfgang needs his mighty hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_DONESWIM = "Wolfgang now definitely made of water."
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_PRESWIM = "Wolfgang feels like swimming"
GLOBAL.STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_NOSWIM = "Wolfgang changed mind, land is better"

GLOBAL.STRINGS.CHARACTERS.WENDY.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WENDY.ANNOUNCE_DONESWIM = "Maybe I should have stayed at the bottom of the sea instead"
GLOBAL.STRINGS.CHARACTERS.WENDY.ANNOUNCE_PRESWIM = "Nobody will see my tears in water"
GLOBAL.STRINGS.CHARACTERS.WENDY.ANNOUNCE_NOSWIM = "Guess I can't hide tears from Abigail"

GLOBAL.STRINGS.CHARACTERS.WX78.ANNOUNCE_SWIMTOOL = "NEEEED HAAAANNNNDDDD MAAAANIIIIIPULLLLLATO000ORS T0 GETTTTTT 0UTTT"
GLOBAL.STRINGS.CHARACTERS.WX78.ANNOUNCE_DONESWIM = "EERRRRO000OR WWAAATEER AAANIIHILAAATION IIMMMMMINNNENT"
GLOBAL.STRINGS.CHARACTERS.WX78.ANNOUNCE_PRESWIM = "I FEEL LIKE KILLING MYSELF"
GLOBAL.STRINGS.CHARACTERS.WX78.ANNOUNCE_NOSWIM = "LEAVE WATER WALLOWING FOR FLESHLINGS"

GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_DONESWIM = "That was refreshing"
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_PRESWIM = "I wonder what the water temperature is"
GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_NOSWIM = "Maybe I can swim after some reading beforehand"

GLOBAL.STRINGS.CHARACTERS.WOODIE.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WOODIE.ANNOUNCE_DONESWIM = "That was refreshing"
GLOBAL.STRINGS.CHARACTERS.WOODIE.ANNOUNCE_PRESWIM = "Time to get wet"
GLOBAL.STRINGS.CHARACTERS.WOODIE.ANNOUNCE_NOSWIM = "Maybe I can swim later"

--maxwell
GLOBAL.STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_DONESWIM = "That was refreshing"
GLOBAL.STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_PRESWIM = "Time to get wet"
GLOBAL.STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_NOSWIM = "Maybe I can swim later"

--wigfrid
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_DONESWIM = "That was refreshing"
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_PRESWIM = "Time to get wet"
GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_NOSWIM = "Maybe I can swim later"

GLOBAL.STRINGS.CHARACTERS.WEBBER.ANNOUNCE_SWIMTOOL = "We need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WEBBER.ANNOUNCE_DONESWIM = "That was refreshing"
GLOBAL.STRINGS.CHARACTERS.WEBBER.ANNOUNCE_PRESWIM = "Time to get wet"
GLOBAL.STRINGS.CHARACTERS.WEBBER.ANNOUNCE_NOSWIM = "Maybe we can swim later"

GLOBAL.STRINGS.CHARACTERS.WARLY.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WARLY.ANNOUNCE_DONESWIM = "That was refreshing"
GLOBAL.STRINGS.CHARACTERS.WARLY.ANNOUNCE_PRESWIM = "Time to get wet"
GLOBAL.STRINGS.CHARACTERS.WARLY.ANNOUNCE_NOSWIM = "Maybe I can swim later"

GLOBAL.STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_SWIMTOOL = "Need my leafs for swimming"
GLOBAL.STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_DONESWIM = "Fully wet"
GLOBAL.STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_PRESWIM = "Time to get wet"
GLOBAL.STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_NOSWIM = "Maybe I can hydrate later"

GLOBAL.STRINGS.CHARACTERS.WINONA.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WINONA.ANNOUNCE_DONESWIM = "That was refreshing"
GLOBAL.STRINGS.CHARACTERS.WINONA.ANNOUNCE_PRESWIM = "Time to get wet"
GLOBAL.STRINGS.CHARACTERS.WINONA.ANNOUNCE_NOSWIM = "Maybe I can swim later"

GLOBAL.STRINGS.CHARACTERS.WORTOX.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WORTOX.ANNOUNCE_DONESWIM = "That was refreshing"
GLOBAL.STRINGS.CHARACTERS.WORTOX.ANNOUNCE_PRESWIM = "Time to get wet"
GLOBAL.STRINGS.CHARACTERS.WORTOX.ANNOUNCE_NOSWIM = "Maybe I can swim later"

GLOBAL.STRINGS.CHARACTERS.WALTER.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WALTER.ANNOUNCE_DONESWIM = "That was refreshing"
GLOBAL.STRINGS.CHARACTERS.WALTER.ANNOUNCE_PRESWIM = "Time to get wet"
GLOBAL.STRINGS.CHARACTERS.WALTER.ANNOUNCE_NOSWIM = "Maybe I can swim later"

GLOBAL.STRINGS.CHARACTERS.WANDA.ANNOUNCE_SWIMTOOL = "Need my hands for swimming"
GLOBAL.STRINGS.CHARACTERS.WANDA.ANNOUNCE_DONESWIM = "That was refreshing"
GLOBAL.STRINGS.CHARACTERS.WANDA.ANNOUNCE_PRESWIM = "Time to soak those old bones"
GLOBAL.STRINGS.CHARACTERS.WANDA.ANNOUNCE_NOSWIM = "Maybe I can swim later ... or before?"